# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('current_credits', models.IntegerField()),
                ('classes_per_quarter', models.IntegerField(default=0)),
                ('major', models.CharField(max_length=50)),
                ('concentration', models.CharField(max_length=4)),
                ('summer', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('class_list', models.CharField(default='', max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
