# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyHome', '0003_auto_20170519_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='asdf',
            fields=[
                ('student_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('current_credits', models.IntegerField()),
                ('classes_per_quarter', models.IntegerField(default=0)),
                ('major', models.CharField(max_length=50)),
                ('concentration', models.CharField(max_length=4)),
                ('summer', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('class_list', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('student_name', models.CharField(max_length=50, verbose_name='student_name')),
                ('student_number', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='student_number')),
                ('current_credits', models.IntegerField(default=0, verbose_name='current_credits')),
                ('classes_per_quarter', models.IntegerField(default=0, verbose_name='classes_per_quarter')),
                ('major', models.CharField(max_length=50, verbose_name='major')),
                ('concentration', models.CharField(max_length=4, verbose_name='concentration')),
                ('summer', models.BooleanField(default=False, verbose_name='summer')),
                ('online', models.BooleanField(default=False, verbose_name='online')),
                ('class_list', models.CharField(default='', max_length=1000, verbose_name='class_list')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ('user',),
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
